-- Create User forum
CREATE USER forum IDENTIFIED BY 1234 DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
/

-- Grant section 1
GRANT CREATE SESSION TO forum
/
GRANT CREATE TABLE TO forum
/
GRANT CREATE PROCEDURE TO forum
/
GRANT CREATE TRIGGER TO forum
/
GRANT CREATE VIEW TO forum
/
GRANT CREATE SEQUENCE TO forum
/
GRANT CREATE VIEW TO forum
/
GRANT CREATE ANY CONTEXT TO forum


-- Grant section 2
GRANT DELETE ANY TABLE TO forum
/
GRANT DROP ANY TABLE TO forum
/
GRANT DROP ANY PROCEDURE TO forum
/
GRANT DROP ANY TRIGGER TO forum
/
GRANT DROP ANY VIEW TO forum
/
GRANT DROP ANY SEQUENCE TO forum
/


-- Grant section 3
GRANT ALTER ANY SEQUENCE TO forum
/
GRANT ALTER ANY TABLE TO forum
/
GRANT ALTER ANY PROCEDURE TO forum
/
GRANT ALTER ANY TRIGGER TO forum
/

COMMIT WORK
/