DROP SEQUENCE FORUM_PARTITION_SEQ;
DROP SEQUENCE USER_ROLE_SEQ;
DROP SEQUENCE FORUM_USER_SEQ;
DROP SEQUENCE FORUM_CATEGORY_SEQ;
DROP SEQUENCE TOPIC_SEQ;
DROP SEQUENCE FORUM_MESSAGE_SEQ;

DROP TABLE FORUM_PARTITION CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE FORUM_USER CASCADE CONSTRAINTS;
DROP TABLE FORUM_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE TOPIC CASCADE CONSTRAINTS;
DROP TABLE FORUM_MESSAGE CASCADE CONSTRAINTS;

DROP TRIGGER AUTOINCREMENT_FORUM_PARTITION;
DROP TRIGGER AUTOINCREMENT_USER_ROLE;
DROP TRIGGER AUTOINCREMENT_FORUM_USER;
DROP TRIGGER AUTOINCREMENT_FORUM_CATEGORY;
DROP TRIGGER AUTOINCREMENT_TOPIC;
DROP TRIGGER AUTOINCREMENT_FORUM_MESSAGE;