CREATE OR REPLACE PROCEDURE GET_USER_BY_EMAIL(
    U_EMAIL VARCHAR2,
    USER_ID OUT NUMBER,
    USER_LOGIN OUT VARCHAR2,
    USER_EMAIL OUT VARCHAR2,
    USER_PASSWORD OUT VARCHAR2,
    USER_REG_DATE OUT DATE,
    ROLE_ID OUT NUMBER,
    ROLE_NAME OUT VARCHAR2) 
IS
BEGIN
    SELECT
        FORUM_USER.ID, FORUM_USER.LOGIN, FORUM_USER.EMAIL, FORUM_USER.PASSWORD, FORUM_USER.REGISTRATION_DATE, USER_ROLE.ID, USER_ROLE.NAME
        INTO USER_ID, USER_LOGIN, USER_EMAIL, USER_PASSWORD, USER_REG_DATE, ROLE_ID, ROLE_NAME
    FROM FORUM_USER
    JOIN USER_ROLE ON USER_ROLE.ID = FORUM_USER.ROLE_ID
    WHERE FORUM_USER.EMAIL = U_EMAIL;
END;