CREATE OR REPLACE PROCEDURE GET_TOPIC_WITH_USER(
    TOPIC_ID NUMBER,
    TOPIC_NAME OUT VARCHAR2,
    CATEGORY_ID OUT VARCHAR2,
    TOPIC_DATE OUT DATE,
    TOPIC_IS_CLOSED OUT NUMBER,
    USER_ID OUT NUMBER,
    USER_LOGIN OUT VARCHAR2,
    USER_EMAIL OUT VARCHAR2,
    USER_REG_DATE OUT DATE,
    ROLE_ID OUT NUMBER,
    ROLE_NAME OUT VARCHAR2)
IS
BEGIN
    SELECT TOPIC.NAME, TOPIC.CATEGORY_ID, TOPIC.PUBLISH_DATE, TOPIC.IS_CLOSED,
    FORUM_USER.ID, FORUM_USER.LOGIN, FORUM_USER.EMAIL, FORUM_USER.REGISTRATION_DATE,
    USER_ROLE.ID, USER_ROLE.NAME
    INTO TOPIC_NAME, CATEGORY_ID, TOPIC_DATE, TOPIC_IS_CLOSED,
    USER_ID, USER_LOGIN, USER_EMAIL, USER_REG_DATE,
    ROLE_ID, ROLE_NAME
    FROM TOPIC
    JOIN FORUM_USER ON FORUM_USER.ID = TOPIC.USER_ID
    LEFT JOIN USER_ROLE ON USER_ROLE.ID = FORUM_USER.ROLE_ID
    WHERE TOPIC.ID = TOPIC_ID;
END;