CREATE OR REPLACE PROCEDURE GET_USERS(
        RESULT_USERS OUT NOCOPY SYS_REFCUSRSOR)
AS
BEGIN
    OPEN RESULT_USERS FOR SELECT id, login, email, registrtion_date, role_id from FORUM_USER
    INNER JOIN USER_ROLE ON FORUM_USER.ROLE_ID = USER_ROLE.ID;
END;