CREATE OR REPLACE PROCEDURE GET_CATEGORY(
        P_ID IN NUMBER,
        CATEGORY_NAME OUT VARCHAR2,
        RESULT_TOPICS OUT NOCOPY SYS_REFCURSOR)
AS
BEGIN
    SELECT NAME AS CATEGORY_NAME
    INTO CATEGORY_NAME
    FROM FORUM_CATEGORY
    WHERE ID = P_ID;
    
    OPEN RESULT_TOPICS FOR
    SELECT 
	NAME AS TOPIC_NAME,
	TOPIC.ID AS TOPIC_ID,
	TOPIC.CATEGORY_ID AS CATEGORY_ID,
	TOPIC.IS_CLOSED AS TOPIC_IS_CLOSED,
	TOPIC.PUBLISH_DATE AS TOPIC_DATE,
    (SELECT COUNT(*) FROM FORUM_MESSAGE WHERE TOPIC_ID = TOPIC.ID) AS MESSAGES_COUNT,
    (SELECT MAX(PUBLISH_DATE) FROM FORUM_MESSAGE WHERE TOPIC_ID = TOPIC.ID) AS LAST_MESSAGE_DATE
    FROM TOPIC WHERE CATEGORY_ID = P_ID;
    
END;
