CREATE OR REPLACE FUNCTION INSERT_CATEGORY(
    P_PARTITION_ID NUMBER,
    P_NAME VARCHAR2,
    P_DESCRIPTION VARCHAR2,
    CATEGORY_ID OUT NUMBER,
    ER OUT VARCHAR2)
RETURN NUMBER
IS
BEGIN
    INSERT INTO FORUM_CATEGORY (NAME, DESCRIPTION, PARTITION_ID) VALUES(P_NAME, P_DESCRIPTION, P_PARTITION_ID);
    SELECT ID INTO CATEGORY_ID FROM FORUM_CATEGORY WHERE PARTITION_ID = P_PARTITION_ID AND NAME = P_NAME AND DESCRIPTION = P_DESCRIPTION;
    RETURN 1;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        ER := 'DELETE_FAILED';
        RETURN 0;
END;