create or replace FUNCTION INSERT_MESSAGE( 
PASS_TEXT VARCHAR2,
PASS_TOPIC_ID NUMBER,
PASS_USER_ID NUMBER, 
MESSAGE_ID OUT NUMBER, 
MESSAGE_DATE OUT DATE,
USER_EMAIL OUT VARCHAR2,
USER_LOGIN OUT VARCHAR2,
USER_REG_DATE OUT DATE, 
ROLE_ID OUT NUMBER,
ROLE_NAME OUT VARCHAR2,
ERR OUT VARCHAR2) RETURN NUMBER 
IS
    COUNT_TOPICS NUMBER;
    COUNT_USERS NUMBER;
    CURRENT_DATE DATE := SYSDATE;
BEGIN 
    SELECT COUNT(*) INTO COUNT_USERS FROM FORUM_USER WHERE ID = PASS_USER_ID;
    SELECT COUNT(*) INTO COUNT_TOPICS FROM TOPIC WHERE ID = PASS_TOPIC_ID;
    IF(COUNT_USERS = 0) THEN 
        ERR:='SUCH USER NOT EXIST'; 
        RETURN 0;
    ELSIF(COUNT_TOPICS = 0) THEN 
        ERR:='SUCH TOPIC NOT EXIST'; 
        RETURN 0;
    ELSE 
        INSERT INTO FORUM_MESSAGE (TEXT,TOPIC_ID,USER_ID,PUBLISH_DATE) VALUES(PASS_TEXT,PASS_TOPIC_ID, PASS_USER_ID, CURRENT_DATE);
        SELECT FORUM_MESSAGE.ID, FORUM_MESSAGE.PUBLISH_DATE, FORUM_USER.EMAIL, FORUM_USER.LOGIN, FORUM_USER.REGISTRATION_DATE, USER_ROLE.ID, USER_ROLE.NAME 
        INTO MESSAGE_ID, MESSAGE_DATE, USER_EMAIL, USER_LOGIN, USER_REG_DATE, ROLE_ID, ROLE_NAME 
        FROM FORUM_MESSAGE 
        JOIN FORUM_USER ON FORUM_USER.ID = FORUM_MESSAGE.USER_ID 
        LEFT JOIN USER_ROLE ON USER_ROLE.ID = FORUM_USER.ROLE_ID 
        WHERE FORUM_MESSAGE.PUBLISH_DATE = CURRENT_DATE AND FORUM_MESSAGE.USER_ID = PASS_USER_ID; RETURN 1; 
    END IF; 
END;