CREATE TABLE FORUM_JOURNAL(
    ACTION_DATE DATE DEFAULT SYSDATE NOT NULL,
    ACTION VARCHAR2(255) NOT NULL,
    USERNAME VARCHAR2(255) NOT NULL
);
/
CREATE OR REPLACE PROCEDURE LOGIN_CONTEXT_ADD(USERNAME VARCHAR2)
IS
BEGIN
    DBMS_SESSION.SET_CONTEXT('LOGIN_CONTEXT', 'USERNAME', USERNAME);
END;
/
CREATE OR REPLACE CONTEXT LOGIN_CONTEXT USING LOGIN_CONTEXT_ADD; 
/
CREATE OR REPLACE TRIGGER FORUM_MESSAGE_JOURNALING
    AFTER INSERT OR UPDATE OR DELETE ON FORUM_MESSAGE
    FOR EACH ROW
DECLARE
    REC_TABLE FORUM_JOURNAL%ROWTYPE;
BEGIN
    CASE
        WHEN INSERTING THEN
            REC_TABLE.ACTION :='INSERT MESSAGE('|| :NEW.ID || ') "' || :NEW.TEXT || '"';
        WHEN UPDATING THEN
            REC_TABLE.ACTION :='UPDATE MESSAGE('|| :NEW.ID || ') "' || :NEW.TEXT || '"';
        WHEN DELETING THEN
            REC_TABLE.ACTION :='DELETE MESSAGE('|| :NEW.ID || ') "' || :OLD.TEXT || '"';
    END CASE;
    REC_TABLE.USERNAME := SYS_CONTEXT('FORUM_CONTEXT', 'USERNAME');
    IF REC_TABLE.USERNAME IS NULL THEN
        RAISE_APPLICATION_ERROR(-20003, 'Username in the context is empty!');
    END IF;
    REC_TABLE.ACTION_DATE := SYSDATE;
    INSERT INTO FORUM_JOURNAL VALUES REC_TABLE;
END;
/
CREATE OR REPLACE TRIGGER FORUM_CATEGORY_JOURNALING
    AFTER INSERT OR UPDATE OR DELETE ON FORUM_CATEGORY
    FOR EACH ROW
DECLARE
    REC_TABLE FORUM_JOURNAL%ROWTYPE;
BEGIN
    CASE
        WHEN INSERTING THEN
            REC_TABLE.ACTION :='INSERT CATEGORY('|| :NEW.ID || ') "' || :NEW.NAME || '"';
        WHEN UPDATING THEN
            REC_TABLE.ACTION :='UPDATE CATEGORY('|| :NEW.ID || ') "' || :NEW.NAME || '"';
        WHEN DELETING THEN
            REC_TABLE.ACTION :='DELETE CATEGORY('|| :NEW.ID || ') "' || :OLD.NAME || '"';
    END CASE;
    REC_TABLE.USERNAME := SYS_CONTEXT('FORUM_CONTEXT', 'USERNAME');
    IF REC_TABLE.USERNAME IS NULL THEN
        RAISE_APPLICATION_ERROR(-20003, 'Username in the context is empty!');
    END IF;
    REC_TABLE.ACTION_DATE := SYSDATE;
    INSERT INTO FORUM_JOURNAL VALUES REC_TABLE;
END;
/
CREATE OR REPLACE TRIGGER FORUM_PARTITION_JOURNALING
    AFTER INSERT OR UPDATE OR DELETE ON FORUM_PARTITION
    FOR EACH ROW
DECLARE
    REC_TABLE FORUM_JOURNAL%ROWTYPE;
BEGIN
    CASE
        WHEN INSERTING THEN
            REC_TABLE.ACTION :='INSERT PARTITION('|| :NEW.ID || ') "' || :NEW.NAME || '"';
        WHEN UPDATING THEN
            REC_TABLE.ACTION :='UPDATE PARTITION('|| :NEW.ID || ') "' || :NEW.NAME || '"';
        WHEN DELETING THEN
            REC_TABLE.ACTION :='DELETE PARTITION('|| :NEW.ID || ') "' || :OLD.NAME || '"';
    END CASE;
    REC_TABLE.USERNAME := SYS_CONTEXT('FORUM_CONTEXT', 'USERNAME');
    IF REC_TABLE.USERNAME IS NULL THEN
        RAISE_APPLICATION_ERROR(-20003, 'Username in the context is empty!');
    END IF;
    REC_TABLE.ACTION_DATE := SYSDATE;
    INSERT INTO FORUM_JOURNAL VALUES REC_TABLE;
END;
/
CREATE OR REPLACE TRIGGER TOPIC_JOURNALING
    AFTER INSERT OR UPDATE OR DELETE ON TOPIC
    FOR EACH ROW
DECLARE
    REC_TABLE FORUM_JOURNAL%ROWTYPE;
BEGIN
    CASE
        WHEN INSERTING THEN
            REC_TABLE.ACTION :='INSERT TOPIC('|| :NEW.ID || ') "' || :NEW.NAME || '"';
        WHEN UPDATING THEN
            REC_TABLE.ACTION :='UPDATE TOPIC('|| :NEW.ID || ') "' || :NEW.NAME || '"';
        WHEN DELETING THEN
            REC_TABLE.ACTION :='DELETE DELETE('|| :NEW.ID || ') "' || :OLD.NAME || '"';
    END CASE;
    REC_TABLE.USERNAME := SYS_CONTEXT('FORUM_CONTEXT', 'USERNAME');
    IF REC_TABLE.USERNAME IS NULL THEN
        RAISE_APPLICATION_ERROR(-20003, 'Username in the context is empty!');
    END IF;
    REC_TABLE.ACTION_DATE := SYSDATE;
    INSERT INTO FORUM_JOURNAL VALUES REC_TABLE;
END;