CREATE OR REPLACE PROCEDURE INSERT_INIT_ROLES 
IS
    ADMIN_NAME VARCHAR2(5) := 'ADMIN';
    USER_NAME VARCHAR2(5) := 'USER';
BEGIN
    INSERT INTO USER_ROLE
    (NAME)
    VALUES (USER_NAME);
    INSERT INTO USER_ROLE
    (NAME)
    VALUES (ADMIN_NAME);
END;