CREATE OR REPLACE PROCEDURE send_mail ( p_message IN VARCHAR2)
AS
    l_mail_conn UTL_SMTP.connection;
    L_MAIL_CONNN UTL_SMTP.connection;
BEGIN
    l_mail_conn := UTL_SMTP.open_connection('smtp.yandex.ru', 465);
    UTL_SMTP.helo(l_mail_conn, 'smtp.yandex.ru');  
    UTL_SMTP.command(l_mail_conn, 'AUTH', 'LOGIN');
    UTL_SMTP.command(l_mail_conn, 'qweqwe123qewqe123@yandex.by');
    UTL_SMTP.command(l_mail_connn,'123qweASD');
    UTL_SMTP.rcpt(l_mail_conn, 'maximspasyonov@yandex.by');
    UTL_SMTP.data(l_mail_conn, p_message || UTL_TCP.crlf || UTL_TCP.crlf);
    UTL_SMTP.quit(l_mail_conn);
END;
/
CREATE OR REPLACE PROCEDURE PREPARE_SEND_MAIL
AS
INSERT_COUNT_MESSAGE NUMBER;
UPDATE_COUNT_MESSAGE NUMBER;
DELETE_COUNT_MESSAGE NUMBER;
INSERT_COUNT_PARTITION NUMBER;
UPDATE_COUNT_PARTITION NUMBER;
DELETE_COUNT_PARTITION NUMBER;
INSERT_COUNT_CATEGORY NUMBER;
UPDATE_COUNT_CATEGORY NUMBER;
DELETE_COUNT_CATEGORY NUMBER;
INSERT_COUNT_TOPIC NUMBER;
DELETE_COUNT_TOPIC NUMBER;
UPDATE_COUNT_TOPIC NUMBER;
MESSAGE VARCHAR2(256);  
BEGIN
    SELECT COUNT(*) INTO INSERT_COUNT_MESSAGE FROM FORUM_JOURNAL
    WHERE action LIKE 'INSERT MESSAGE%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO UPDATE_COUNT_MESSAGE FROM FORUM_JOURNAL
    WHERE action LIKE 'UPDATE MESSAGE%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO DELETE_COUNT_MESSAGE FROM FORUM_JOURNAL
    WHERE action LIKE 'DELETE MESSAGE%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO INSERT_COUNT_PARTITION FROM FORUM_JOURNAL
    WHERE action LIKE 'INSERT PARTITION%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO UPDATE_COUNT_PARTITION FROM FORUM_JOURNAL
    WHERE action LIKE 'UPDATE PARTITION%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO DELETE_COUNT_PARTITION FROM FORUM_JOURNAL
    WHERE action LIKE 'DELETE PARTITION' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO INSERT_COUNT_CATEGORY FROM FORUM_JOURNAL
    WHERE action LIKE 'INSERT CATEGORY%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO UPDATE_COUNT_CATEGORY FROM FORUM_JOURNAL
    WHERE action LIKE 'UPDATE CATEGORY%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO DELETE_COUNT_CATEGORY FROM FORUM_JOURNAL
    WHERE action LIKE 'DELETE CATEGORY' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO INSERT_COUNT_TOPIC FROM FORUM_JOURNAL
    WHERE action LIKE 'INSERT TOPIC%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO UPDATE_COUNT_TOPIC FROM FORUM_JOURNAL
    WHERE action LIKE 'UPDATE TOPIC%' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    SELECT COUNT(*) INTO DELETE_COUNT_TOPIC FROM FORUM_JOURNAL
    WHERE action LIKE 'DELETE TOPIC' and action_date =  (select TO_CHAR(sysdate, 'DD.MM.YY') FROM DUAL);
    
    MESSAGE := 'TOTAL NEW MESSAGE: ' || INSERT_COUNT_MESSAGE || ' TOTAL UPDATE MESSAGE: ' || UPDATE_COUNT_MESSAGE || ' TOTAL DELETE MESSAGE: ' || DELETE_COUNT_MESSAGE
            || 'TOTAL NEW PARTITION: ' || insert_count_partition || 'TOTAL UPDATE PARTITION: ' || UPDATE_COUNT_PARTITION || 'TOTAL DELETE PARTITION: ' || DELETE_COUNT_PARTITION
            || 'TOTAL NEW CATEGORY: ' || INSERT_COUNT_CATEGORY || ' TOTAL UPDATE CATEGORY: ' || UPDATE_COUNT_CATEGORY || ' TOTAL DELETE CATEGORY: ' || DELETE_COUNT_CATEGORY
            ||  'TOTAL NEW TOPIC: ' || INSERT_COUNT_TOPIC || ' TOTAL UPDATE TOPIC: ' || UPDATE_COUNT_TOPIC || ' TOTAL DELETE TOPIC: ' || DELETE_COUNT_TOPIC;
    SEND_MAIL(MESSAGE);
END;
/
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'SEND_MAIL_JOB',
JOB_TYPE => 'PLSQL_BLOCK',
JOB_ACTION => ' BEGIN
                 PREPARE_SEND_MAIL();
                END;',
REPEAT_INTERVAL => 'FREQ=DAILY;INTERVAL=1',
ENABLED => TRUE);
 END;