CREATE OR REPLACE FUNCTION UPDATE_TOPIC_IS_CLOSED(PASS_ID NUMBER, PASS_CLOSED NUMBER)
RETURN NUMBER
IS
BEGIN
 UPDATE TOPIC
 SET IS_CLOSED = PASS_CLOSED
 WHERE ID = PASS_ID;
 RETURN 1;
EXCEPTION
WHEN OTHERS THEN
    RETURN 0;
END;