CREATE OR REPLACE FUNCTION UPDATE_MESSAGE(PASS_ID NUMBER, PASS_TEXT VARCHAR2)
RETURN NUMBER
AS
BEGIN
 UPDATE FORUM_MESSAGE
 SET TEXT = PASS_TEXT
 WHERE ID = PASS_ID;
 RETURN 1;
EXCEPTION
WHEN OTHERS THEN
    RETURN 0;
END;
