CREATE OR REPLACE FUNCTION UPDATE_CATEGORY(
        P_ID IN NUMBER,
        NEW_NAME IN VARCHAR2,
        ER OUT VARCHAR2)
        RETURN NUMBER
AS
BEGIN
    UPDATE FORUM_CATEGORY
    SET NAME = NEW_NAME WHERE ID = P_ID;
    RETURN 1;
EXCEPTION
    WHEN OTHERS THEN
        ER:= 'Update failed for category';
    RETURN 0;
END;
