CREATE OR REPLACE FUNCTION UPDATE_CATEGORY(
        P_ID IN NUMBER,
        P_NAME IN VARCHAR2,
		P_DESCRIPTION IN VARCHAR2,
		P_PARTITION_ID IN VARCHAR2,
        ER OUT VARCHAR2)
        RETURN NUMBER
AS
BEGIN
    UPDATE FORUM_CATEGORY
    SET NAME = P_NAME, DESCRIPTION = P_DESCRIPTION, PARTITION_ID = P_PARTITION_ID WHERE ID = P_ID;
    RETURN 1;
EXCEPTION
    WHEN OTHERS THEN
        ER:= 'Update failed for category';
    RETURN 0;
END;
